//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProManService
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOC
    {
        public long ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ProjectRepositoryID { get; set; }
        public int DeveloperID { get; set; }
        public Nullable<int> FileTypeID { get; set; }
        public int FileID { get; set; }
        public long Bytes { get; set; }
        public string Type { get; set; }
        public long RevisionNumber { get; set; }
        public System.DateTime DT { get; set; }
    
        public virtual File File { get; set; }
        public virtual ProjectRepository ProjectRepository { get; set; }
        public virtual Developer Developer { get; set; }
        public virtual FileType FileType { get; set; }
        public virtual Project Project { get; set; }
    }
}
