//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProManService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public long ID { get; set; }
        public string FileURL { get; set; }
        public string ErrorMessage { get; set; }
        public System.DateTime dt { get; set; }
    }
}
