//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProManService
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.BOCs = new HashSet<BOC>();
        }
    
        public int ID { get; set; }
        public string Filename { get; set; }
    
        public virtual ICollection<BOC> BOCs { get; set; }
    }
}
