//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProManService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectHistory
    {
        public int ID { get; set; }
        public int ProjectRepositoryID { get; set; }
        public int DeveloperID { get; set; }
        public long Bytes { get; set; }
        public System.DateTime LastDT { get; set; }
        public long LastRevision { get; set; }
    
        public virtual Developer Developer { get; set; }
        public virtual ProjectRepository ProjectRepository { get; set; }
    }
}
