//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProManService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repository
    {
        public Repository()
        {
            this.ProjectRepositories = new HashSet<ProjectRepository>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string BaseUrl { get; set; }
        public string RootUsername { get; set; }
        public string RootPassword { get; set; }
        public string SourceUrl { get; set; }
        public long LastRevision { get; set; }
    
        public virtual ICollection<ProjectRepository> ProjectRepositories { get; set; }
    }
}
