//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Site {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Site() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProManClient.Resources.Site", typeof(Site).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αdditions.
        /// </summary>
        public static string lbl_add {
            get {
                return ResourceManager.GetString("lbl_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Month.
        /// </summary>
        public static string lbl_current_month {
            get {
                return ResourceManager.GetString("lbl_current_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Week.
        /// </summary>
        public static string lbl_current_week {
            get {
                return ResourceManager.GetString("lbl_current_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletions.
        /// </summary>
        public static string lbl_del {
            get {
                return ResourceManager.GetString("lbl_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Month.
        /// </summary>
        public static string lbl_last_month {
            get {
                return ResourceManager.GetString("lbl_last_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Week.
        /// </summary>
        public static string lbl_last_week {
            get {
                return ResourceManager.GetString("lbl_last_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifications.
        /// </summary>
        public static string lbl_mod {
            get {
                return ResourceManager.GetString("lbl_mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Month.
        /// </summary>
        public static string lbl_month {
            get {
                return ResourceManager.GetString("lbl_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan..
        /// </summary>
        public static string lbl_month1 {
            get {
                return ResourceManager.GetString("lbl_month1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct..
        /// </summary>
        public static string lbl_month10 {
            get {
                return ResourceManager.GetString("lbl_month10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov..
        /// </summary>
        public static string lbl_month11 {
            get {
                return ResourceManager.GetString("lbl_month11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec..
        /// </summary>
        public static string lbl_month12 {
            get {
                return ResourceManager.GetString("lbl_month12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb..
        /// </summary>
        public static string lbl_month2 {
            get {
                return ResourceManager.GetString("lbl_month2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar..
        /// </summary>
        public static string lbl_month3 {
            get {
                return ResourceManager.GetString("lbl_month3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr..
        /// </summary>
        public static string lbl_month4 {
            get {
                return ResourceManager.GetString("lbl_month4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May..
        /// </summary>
        public static string lbl_month5 {
            get {
                return ResourceManager.GetString("lbl_month5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun..
        /// </summary>
        public static string lbl_month6 {
            get {
                return ResourceManager.GetString("lbl_month6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul..
        /// </summary>
        public static string lbl_month7 {
            get {
                return ResourceManager.GetString("lbl_month7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug..
        /// </summary>
        public static string lbl_month8 {
            get {
                return ResourceManager.GetString("lbl_month8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep..
        /// </summary>
        public static string lbl_month9 {
            get {
                return ResourceManager.GetString("lbl_month9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Month.
        /// </summary>
        public static string lbl_previous_month {
            get {
                return ResourceManager.GetString("lbl_previous_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Week.
        /// </summary>
        public static string lbl_previous_week {
            get {
                return ResourceManager.GetString("lbl_previous_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string lbl_today {
            get {
                return ResourceManager.GetString("lbl_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string lbl_total {
            get {
                return ResourceManager.GetString("lbl_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Week.
        /// </summary>
        public static string lbl_week {
            get {
                return ResourceManager.GetString("lbl_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string lbl_yesterday {
            get {
                return ResourceManager.GetString("lbl_yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users.
        /// </summary>
        public static string lblAllUsers {
            get {
                return ResourceManager.GetString("lblAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minute ago.
        /// </summary>
        public static string lblAMinuteAgo {
            get {
                return ResourceManager.GetString("lblAMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An hour ago.
        /// </summary>
        public static string lblAnHourAgo {
            get {
                return ResourceManager.GetString("lblAnHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commited Files.
        /// </summary>
        public static string lblCommitedFiles {
            get {
                return ResourceManager.GetString("lblCommitedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm discard changes.
        /// </summary>
        public static string lblConfirmDiscardChanges {
            get {
                return ResourceManager.GetString("lblConfirmDiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgaria.
        /// </summary>
        public static string lblCountry_bulgaria {
            get {
                return ResourceManager.GetString("lblCountry_bulgaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        public static string lblCountry_germany {
            get {
                return ResourceManager.GetString("lblCountry_germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greece.
        /// </summary>
        public static string lblCountry_greece {
            get {
                return ResourceManager.GetString("lblCountry_greece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        public static string lblCountry_italy {
            get {
                return ResourceManager.GetString("lblCountry_italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        public static string lblCountry_sweden {
            get {
                return ResourceManager.GetString("lblCountry_sweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Updates.
        /// </summary>
        public static string lblDataUpdates {
            get {
                return ResourceManager.GetString("lblDataUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days ago.
        /// </summary>
        public static string lblDaysAgo {
            get {
                return ResourceManager.GetString("lblDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes.
        /// </summary>
        public static string lblDiscardChanges {
            get {
                return ResourceManager.GetString("lblDiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes?.
        /// </summary>
        public static string lblDiscardChangesQuestion {
            get {
                return ResourceManager.GetString("lblDiscardChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Confirmation Email.
        /// </summary>
        public static string lble916SendConfEmail {
            get {
                return ResourceManager.GetString("lble916SendConfEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string lblEmailRequired {
            get {
                return ResourceManager.GetString("lblEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lblEnglish {
            get {
                return ResourceManager.GetString("lblEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string lblEnglishShort {
            get {
                return ResourceManager.GetString("lblEnglishShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Page Doesn&apos;t Exist!.
        /// </summary>
        public static string lblError404 {
            get {
                return ResourceManager.GetString("lblError404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some reason the page you are looking for doesn&apos;t exist! It may have been removed from the website or you may have mistyped the url. Anyway, no harm done..
        /// </summary>
        public static string lblError404Description {
            get {
                return ResourceManager.GetString("lblError404Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        public static string lblError500 {
            get {
                return ResourceManager.GetString("lblError500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong that it wasn&apos;t supposed to!.
        /// </summary>
        public static string lblError500Description {
            get {
                return ResourceManager.GetString("lblError500Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation code is not valid or has expired! .
        /// </summary>
        public static string lblError901 {
            get {
                return ResourceManager.GetString("lblError901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation code is not valid or has expired!.
        /// </summary>
        public static string lblError901Description {
            get {
                return ResourceManager.GetString("lblError901Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password!.
        /// </summary>
        public static string lblError902 {
            get {
                return ResourceManager.GetString("lblError902", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password!.
        /// </summary>
        public static string lblError902Description {
            get {
                return ResourceManager.GetString("lblError902Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed guest user!.
        /// </summary>
        public static string lblError903 {
            get {
                return ResourceManager.GetString("lblError903", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed guest user!.
        /// </summary>
        public static string lblError903Description {
            get {
                return ResourceManager.GetString("lblError903Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest user is required!.
        /// </summary>
        public static string lblError904 {
            get {
                return ResourceManager.GetString("lblError904", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest user is required!.
        /// </summary>
        public static string lblError904Description {
            get {
                return ResourceManager.GetString("lblError904Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN for verification!.
        /// </summary>
        public static string lblError905 {
            get {
                return ResourceManager.GetString("lblError905", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN for verification!.
        /// </summary>
        public static string lblError905Description {
            get {
                return ResourceManager.GetString("lblError905Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification period expired!.
        /// </summary>
        public static string lblError906 {
            get {
                return ResourceManager.GetString("lblError906", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification period expired!.
        /// </summary>
        public static string lblError906Description {
            get {
                return ResourceManager.GetString("lblError906Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password reminder key has expired!.
        /// </summary>
        public static string lblError907 {
            get {
                return ResourceManager.GetString("lblError907", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the Description of the error 907.
        /// </summary>
        public static string lblError907Description {
            get {
                return ResourceManager.GetString("lblError907Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user/email is already registered!.
        /// </summary>
        public static string lblError908 {
            get {
                return ResourceManager.GetString("lblError908", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user/email is already registered!.
        /// </summary>
        public static string lblError908Description {
            get {
                return ResourceManager.GetString("lblError908Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Error.
        /// </summary>
        public static string lblError916 {
            get {
                return ResourceManager.GetString("lblError916", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not confirmed.
        /// </summary>
        public static string lblError916Description {
            get {
                return ResourceManager.GetString("lblError916Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmation mail has been submitted to.
        /// </summary>
        public static string lblError916submitted {
            get {
                return ResourceManager.GetString("lblError916submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change Failed.
        /// </summary>
        public static string lblError919 {
            get {
                return ResourceManager.GetString("lblError919", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change Failed.
        /// </summary>
        public static string lblError919Description {
            get {
                return ResourceManager.GetString("lblError919Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 9xx.
        /// </summary>
        public static string lblError9xx {
            get {
                return ResourceManager.GetString("lblError9xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 9xx.
        /// </summary>
        public static string lblError9xxDescription {
            get {
                return ResourceManager.GetString("lblError9xxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string lblFirstname {
            get {
                return ResourceManager.GetString("lblFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname is required.
        /// </summary>
        public static string lblFirstnameRequired {
            get {
                return ResourceManager.GetString("lblFirstnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ελληνικά.
        /// </summary>
        public static string lblGreek {
            get {
                return ResourceManager.GetString("lblGreek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΕΛ.
        /// </summary>
        public static string lblGreekShort {
            get {
                return ResourceManager.GetString("lblGreekShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours ago.
        /// </summary>
        public static string lblHoursAgo {
            get {
                return ResourceManager.GetString("lblHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours before..
        /// </summary>
        public static string lblHoursBefore {
            get {
                return ResourceManager.GetString("lblHoursBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email format is not valid.
        /// </summary>
        public static string lblInvalidEmailFormat {
            get {
                return ResourceManager.GetString("lblInvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just now.
        /// </summary>
        public static string lblJustNow {
            get {
                return ResourceManager.GetString("lblJustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        public static string lblLastMonth {
            get {
                return ResourceManager.GetString("lblLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string lblLastname {
            get {
                return ResourceManager.GetString("lblLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname is required.
        /// </summary>
        public static string lblLastnameRequired {
            get {
                return ResourceManager.GetString("lblLastnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        public static string lblLastWeek {
            get {
                return ResourceManager.GetString("lblLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last year.
        /// </summary>
        public static string lblLastYear {
            get {
                return ResourceManager.GetString("lblLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string lblLoginError {
            get {
                return ResourceManager.GetString("lblLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string lblMenu_account {
            get {
                return ResourceManager.GetString("lblMenu_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Notifications.
        /// </summary>
        public static string lblMenu_conflictnotifications {
            get {
                return ResourceManager.GetString("lblMenu_conflictnotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string lblMenu_contact {
            get {
                return ResourceManager.GetString("lblMenu_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditors.
        /// </summary>
        public static string lblMenu_creditors {
            get {
                return ResourceManager.GetString("lblMenu_creditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string lblMenu_customers {
            get {
                return ResourceManager.GetString("lblMenu_customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string lblMenu_dashboard {
            get {
                return ResourceManager.GetString("lblMenu_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Transactions.
        /// </summary>
        public static string lblMenu_dashboardperusertrader {
            get {
                return ResourceManager.GetString("lblMenu_dashboardperusertrader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtors.
        /// </summary>
        public static string lblMenu_debtors {
            get {
                return ResourceManager.GetString("lblMenu_debtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string lblMenu_form {
            get {
                return ResourceManager.GetString("lblMenu_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month View.
        /// </summary>
        public static string lblMenu_monthview {
            get {
                return ResourceManager.GetString("lblMenu_monthview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Company.
        /// </summary>
        public static string lblMenu_my_company {
            get {
                return ResourceManager.GetString("lblMenu_my_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string lblMenu_notifications {
            get {
                return ResourceManager.GetString("lblMenu_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month View.
        /// </summary>
        public static string lblMenu_oblg_month_view {
            get {
                return ResourceManager.GetString("lblMenu_oblg_month_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week View.
        /// </summary>
        public static string lblMenu_oblg_week_view {
            get {
                return ResourceManager.GetString("lblMenu_oblg_week_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendars.
        /// </summary>
        public static string lblMenu_obligations {
            get {
                return ResourceManager.GetString("lblMenu_obligations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string lblMenu_overview {
            get {
                return ResourceManager.GetString("lblMenu_overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string lblMenu_payments {
            get {
                return ResourceManager.GetString("lblMenu_payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per User.
        /// </summary>
        public static string lblMenu_peruser {
            get {
                return ResourceManager.GetString("lblMenu_peruser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        public static string lblMenu_purchases {
            get {
                return ResourceManager.GetString("lblMenu_purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipts.
        /// </summary>
        public static string lblMenu_receipts {
            get {
                return ResourceManager.GetString("lblMenu_receipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string lblMenu_reports {
            get {
                return ResourceManager.GetString("lblMenu_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string lblMenu_sales {
            get {
                return ResourceManager.GetString("lblMenu_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string lblMenu_settings {
            get {
                return ResourceManager.GetString("lblMenu_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string lblMenu_sign_out {
            get {
                return ResourceManager.GetString("lblMenu_sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string lblMenu_suppliers {
            get {
                return ResourceManager.GetString("lblMenu_suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traders.
        /// </summary>
        public static string lblMenu_traders {
            get {
                return ResourceManager.GetString("lblMenu_traders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string lblMenu_transactions {
            get {
                return ResourceManager.GetString("lblMenu_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Αccount.
        /// </summary>
        public static string lblMenu_useraccount {
            get {
                return ResourceManager.GetString("lblMenu_useraccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string lblMenu_verify {
            get {
                return ResourceManager.GetString("lblMenu_verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week View.
        /// </summary>
        public static string lblMenu_weekview {
            get {
                return ResourceManager.GetString("lblMenu_weekview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes ago.
        /// </summary>
        public static string lblMinutesAgo {
            get {
                return ResourceManager.GetString("lblMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes before..
        /// </summary>
        public static string lblMinutesBefore {
            get {
                return ResourceManager.GetString("lblMinutesBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months ago.
        /// </summary>
        public static string lblMonthsAgo {
            get {
                return ResourceManager.GetString("lblMonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string lblNow {
            get {
                return ResourceManager.GetString("lblNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string lblOk {
            get {
                return ResourceManager.GetString("lblOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string lblPasswordRequired {
            get {
                return ResourceManager.GetString("lblPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload image file of type jpg | jpeg | png | gif.
        /// </summary>
        public static string lblPleaseUploadImageType {
            get {
                return ResourceManager.GetString("lblPleaseUploadImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Home Page.
        /// </summary>
        public static string lblReturnHome {
            get {
                return ResourceManager.GetString("lblReturnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string lblSaveChanges {
            get {
                return ResourceManager.GetString("lblSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search  for a Developer or Project....
        /// </summary>
        public static string lblSearchForADeveloperProject {
            get {
                return ResourceManager.GetString("lblSearchForADeveloperProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a developer.
        /// </summary>
        public static string lblSearchForDevelopers {
            get {
                return ResourceManager.GetString("lblSearchForDevelopers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a project.
        /// </summary>
        public static string lblSearchForProject {
            get {
                return ResourceManager.GetString("lblSearchForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds ago.
        /// </summary>
        public static string lblSecondsAgo {
            get {
                return ResourceManager.GetString("lblSecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a developer.
        /// </summary>
        public static string lblSelectADevelopers {
            get {
                return ResourceManager.GetString("lblSelectADevelopers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a  project.
        /// </summary>
        public static string lblSelectAProject {
            get {
                return ResourceManager.GetString("lblSelectAProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string lblSend {
            get {
                return ResourceManager.GetString("lblSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong! Please try again..
        /// </summary>
        public static string lblSomethingWentWrong {
            get {
                return ResourceManager.GetString("lblSomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string lblUserNameRequired {
            get {
                return ResourceManager.GetString("lblUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Options.
        /// </summary>
        public static string lblUserOptions {
            get {
                return ResourceManager.GetString("lblUserOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong VAT.
        /// </summary>
        public static string lblVATError {
            get {
                return ResourceManager.GetString("lblVATError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string lblVATNumber {
            get {
                return ResourceManager.GetString("lblVATNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks ago.
        /// </summary>
        public static string lblWeeksAgo {
            get {
                return ResourceManager.GetString("lblWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years ago.
        /// </summary>
        public static string lblYearsAgo {
            get {
                return ResourceManager.GetString("lblYearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes have not been saved..
        /// </summary>
        public static string lblYourChangesHaveNotBeenSaved {
            get {
                return ResourceManager.GetString("lblYourChangesHaveNotBeenSaved", resourceCulture);
            }
        }
    }
}
