//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProManClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOC
    {
        public long ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ProjectRepositoryID { get; set; }
        public int DeveloperID { get; set; }
        public Nullable<int> FileTypeID { get; set; }
        public int FileID { get; set; }
        public long Bytes { get; set; }
        public string Type { get; set; }
        public long RevisionNumber { get; set; }
        public System.DateTime DT { get; set; }
        public decimal Change_OFF { get; set; }
    
        public virtual Files Files { get; set; }
        public virtual ProjectRepositories ProjectRepositories { get; set; }
        public virtual Developers Developers { get; set; }
        public virtual FileTypes FileTypes { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
