//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProManClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTypes
    {
        public FileTypes()
        {
            this.BOC = new HashSet<BOC>();
            this.Projects = new HashSet<Projects>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string RemovesRegExp { get; set; }
        public int BPL { get; set; }
    
        public virtual ICollection<BOC> BOC { get; set; }
        public virtual ICollection<Projects> Projects { get; set; }
    }
}
