//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProManClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public Projects()
        {
            this.BOC = new HashSet<BOC>();
            this.ProjectRepositories = new HashSet<ProjectRepositories>();
            this.Developers = new HashSet<Developers>();
            this.FileTypes = new HashSet<FileTypes>();
        }
    
        public int ID { get; set; }
        public int RepositoryID_OFF { get; set; }
        public string Name { get; set; }
        public string Descr { get; set; }
        public string ExcludeRegExp { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BOC> BOC { get; set; }
        public virtual ICollection<ProjectRepositories> ProjectRepositories { get; set; }
        public virtual ICollection<Developers> Developers { get; set; }
        public virtual ICollection<FileTypes> FileTypes { get; set; }
    }
}
